version: '3'

services:
  database:
    image: mysql:8.0.32
    restart: always
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3307:3306"
    volumes:
      - database_data:/var/lib/mysql:rw

volumes:
  database_data:
